### PR TITLE
Support writing sequencefiles

### PR DESCRIPTION
**Pull request by vasi-stripe**
Supports pretty much everything we know how to read: all four Writable types, record and block compression (gzip or snappy).

### CODE REVIEW

**Comment by vasi-stripe** [comment]
Huh, and there's already a PR for this: https://github.com/colinmarc/sequencefile/pull/4

The approaches are similar. Main differences is my branch has more tests, and has a different signature to `Append()`, using interface{} instead of []byte.

**Comment by colinmarc** [comment]
@vasi-stripe I managed to just see this (apparently I didn't have notifications set up for this repo). Are you using this branch internally, and if so do you want to just move this repo over to the public stripe org?

**Comment by vasi-stripe** [comment]
Only using this branch for testing, don't care much what happens to it. Thanks though!

**Comment by colinmarc** [comment]
Finally got a chance to read through this, and I have exactly 0️⃣  comments or suggestions or even nitpicks. Thanks so much for the great contribution!

**Pull request merged**
