### PR TITLE
Implement BZip2 reader compression

### PR DESCRIPTION
**Pull request by streadway**
This is #6 with some tests.

I included the generator for the tests for reference and future/existing test generation.

### CODE REVIEW

**Comment by colinmarc** [comment]
Two changes, then I think this is perfect:

 - `BZip` => `Bzip` (I think that's slightly more correct, but who knows.)
 - You can delete the java file, we don't need it.

**Comment by colinmarc** [comment]
Also, can you add tests here? https://github.com/colinmarc/sequencefile/blob/85dfc1ad587c9ef069e2fb3c9e0eb5a1ea557381/writer_test.go#L91-L97

**Comment by streadway** [comment]
> Also, can you add tests here?
> 
> [sequencefile/writer_test.go](https://github.com/colinmarc/sequencefile/blob/85dfc1ad587c9ef069e2fb3c9e0eb5a1ea557381/writer_test.go#L91-L97)
> 
> Lines 91 to 97 in [85dfc1a](/colinmarc/sequencefile/commit/85dfc1ad587c9ef069e2fb3c9e0eb5a1ea557381)
> 
>  compressions := []compressionSpec{ 
>  	{NoCompression, 0}, 
>  	{RecordCompression, GzipCompression}, 
>  	{RecordCompression, SnappyCompression}, 
>  	{BlockCompression, GzipCompression}, 
>  	{BlockCompression, SnappyCompression}, 
>  }

This change implements the reader for bzip2 compression so I expected the writer to arrive with a different change. Sorry that wasn't clear.

**Comment by streadway** [comment]
The reader was straightforward because the stdlib contains a bzip2 decoder. A stdlib encoder is being tracked on https://github.com/golang/go/issues/4828.

An encoder, and alternative decoder is also available at https://godoc.org/github.com/dsnet/compress/bzip2 should someone want to pick that up.

**Comment by colinmarc** [comment]
Merged (a few years later!) with write support in a35f809372920a36b3f4b6254fe9eedb36266197.

**Pull request closed without merging**
