### PR TITLE
Support reading sequencefiles using zlib compression

### PR DESCRIPTION
**Pull request by praboud-stripe**
This does pretty much what it says on the tin, and the implementation is pretty straightforward.

I also did a bit of drive-by-refactoring around the re-use of the codec class name constants, so that the switch statements uses a reference to the constant, instead of hard-coding the value again.

### CODE REVIEW

**Comment by colinmarc** [comment]
Hi! :D 

I merged your pr in 4ae11a2. Thanks for the contribution! I've seen some activity from Stripe on this repo recently - if you're mantaining an internal fork and want to just move this over to github.com/stripe and maintain it instead, I'd be cool with that.

**Comment by carl-stripe** [comment]
Hi @colinmarc! ✨ 

I think we're willing to take on the project if you'd like (we don't have an internal fork, and are happy with submitting patches we write upstream to you, but we seem to be larger users of this package than many). Let me know?

**Comment by colinmarc** [comment]
It's a carl!!!!!!!!! 🕺 

I offered thinking that it might be inconvenient for you folks with me maintaining it - but if you're not fussed either way then I'll keep it. Thanks! Don't hesitate to reach out if the situation changes.

Also, I've fixed my notifications, so I should be able to actually respond to PRs in a timely manner now. I'll merge #5 in a hot second.

**Comment by carl-stripe** [comment]
ok! works for me :)

**Pull request closed without merging**
